2025-10-25 02:28:30,454 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-10-25 02:28:33,748 [INFO] logging in using static token
2025-10-25 02:28:33,748 [INFO] Session ID: d103df9a8faebdcf1635bcee23d4a833bffde4f59c2d3ae192f264fdca29e03b
2025-10-25 02:28:35,358 [INFO] Shard ID None has connected to Gateway (Session ID: cbe343a0a1660c16cd610efa8e230c55).
2025-10-25 02:28:37,375 [INFO] Logged in as BestBotEver!!!#9403 (ID: 1386280922218893465)
2025-10-25 02:28:37,376 [INFO] No startmessage set.
2025-10-25 02:28:37,971 [INFO] 1431363782155698327:p.pumpum (1260198579067420722) in #ü§ñ-bot-test-üõ†Ô∏è (1399900695993253970): !jvc
2025-10-25 02:28:37,972 [INFO] [COMMAND] jvc called by p.pumpum | mode=None | id=None
2025-10-25 02:28:37,972 [INFO] [INFO] Attempt 1: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:37,972 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:42,262 [INFO] 1431363799750803506:p.pumpum (1260198579067420722) in #ü§ñ-bot-test-üõ†Ô∏è (1399900695993253970): !jvc
2025-10-25 02:28:42,263 [INFO] [COMMAND] jvc called by p.pumpum | mode=None | id=None
2025-10-25 02:28:42,264 [INFO] [INFO] Attempt 1: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:42,264 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:42,998 [INFO] [INFO] Attempt 2: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:42,998 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:47,278 [INFO] [INFO] Attempt 2: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:47,278 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:48,005 [INFO] [INFO] Attempt 3: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:48,006 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:52,284 [INFO] [INFO] Attempt 3: connecting to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ (1375101122246873120)...
2025-10-25 02:28:52,284 [ERROR] [ERROR] Unexpected connection error: PyNaCl library needed in order to use voice
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 1648, in attempt_connect
    vc = await channel.connect(reconnect=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\abc.py", line 2141, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "D:\TonpalmUnmain\Project\BestDiscordBotEver\.venv\Lib\site-packages\discord\voice_client.py", line 220, in __init__
    raise RuntimeError('PyNaCl library needed in order to use voice')
RuntimeError: PyNaCl library needed in order to use voice
2025-10-25 02:28:53,613 [INFO] 1431363847176061042:BestBotEver!!!#9403 (1386280922218893465) in #ü§ñ-bot-test-üõ†Ô∏è (1399900695993253970): Failed to connect after multiple attempts.
2025-10-25 02:28:53,671 [ERROR] [FATAL] Failed to connect to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ after retries.
2025-10-25 02:28:53,672 [INFO] Command completed: jvc by p.pumpum
2025-10-25 02:28:57,930 [INFO] 1431363865689722972:BestBotEver!!!#9403 (1386280922218893465) in #ü§ñ-bot-test-üõ†Ô∏è (1399900695993253970): Failed to connect after multiple attempts.
2025-10-25 02:28:57,987 [ERROR] [FATAL] Failed to connect to ‡πÑ‡∏ö‡∏•‡∏≤‡∏ß‡πÇ‡∏ï‡∏°‡∏≤‡∏ß‡∏µ‡∏°‡∏ß‡∏µ‡∏°//üó£ after retries.
2025-10-25 02:28:57,987 [INFO] Command completed: jvc by p.pumpum
